export enum CounterActionEnum {
  'INCREMENT_COUNT' = 'INCREMENT_COUNT',
  'DECREMENT_COUNT' = 'DECREMENT_COUNT',
  'ADD_COUNT_START' = 'ADD_COUNT_START',
  'ADD_COUNT_SUCCESS' = 'ADD_COUNT_SUCCESS',
  'DECREASE_COUNT' = 'DECREASE_COUNT',
}
